from selenium import webdriver
driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
driver.get('https://practice.automationtesting.in/')
driver.maximize_window()
driver.execute_script("window.scrollBy(0, 600);")
book_selenium_ruby = driver.find_element_by_css_selector('.post-160 h3')
book_selenium_ruby.click()
reviews = driver.find_element_by_css_selector('li>[href="#tab-reviews"]')
reviews.click()
stars = driver.find_element_by_css_selector('#reviews .star-5')
stars.click()
comment = driver.find_element_by_id('comment')
comment.send_keys('Nice book!')
author = driver.find_element_by_id('author')
author.send_keys('Ivan')
e_mail = driver.find_element_by_id('email')
e_mail.send_keys('IO@email.com')
checkbox = driver.find_element_by_id('wp-comment-cookies-consent')
checkbox.click()
submit = driver.find_element_by_id('submit')
submit.click()
driver.quit()
